version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: quarkus_db
      POSTGRES_USER: xander
      POSTGRES_PASSWORD: mypsql
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./src/main/resources/database.sql:/docker-entrypoint-initdb.d/database.sql

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres_db:5432/quarkus_db
      - QUARKUS_DATASOURCE_USERNAME=xander
      - QUARKUS_DATASOURCE_PASSWORD=mypsql
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update

volumes:
  pg_data: