version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: quarkus_db
      POSTGRES_USER: xander
      POSTGRES_PASSWORD: mypsql
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./src/main/resources/database.sql:/docker-entrypoint-initdb.d/database.sql

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres_db:5432/quarkus_db
      - QUARKUS_DATASOURCE_USERNAME=xander
      - QUARKUS_DATASOURCE_PASSWORD=mypsql
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update
      #- QUARKUS_OIDC_AUTH_SERVER_URL=https://accounts.google.com
      #- QUARKUS_OIDC_CLIENT_ID=9456972959-e40npvfni26ur4b2qr9uvhm7h0nbvehv.apps.googleusercontent.com
      #- QUARKUS_OIDC_CREDENTIALS_SECRET=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
      #- QUARKUS_OIDC_APPLICATION_TYPE=web-app
      #- QUARKUS_OIDC_AUTHENTICATION_SCOPES=email

volumes:
  pg_data: